### ISSUE TITLE
PythonX 小组第一次线上碰头会

### ISSUE THREAD

**Issue by simonechen** [TineeOne/PythonX#1]
三位小伙伴，一起来线上碰面，讨论一下咱们的项目吧~

时间： 170304（8wd6） 晚

方式：Zoom

人员：@13416136446   @lying87  @Twanjun  @TineeOne

内容：拟确定项目名称，分解项目，了解 GitHub 协同开发流程

##### 参考资料：

* [HbFinalTaskIdea · AIMinder/Py103 Wiki](https://github.com/AIMinder/Py103/wiki/HbFinalTaskIdea)
* [GitHub flow - User Documentation](https://help.github.com/articles/github-flow/)
* [如何正确的使用github进行项目的协同开发? - 知乎](https://www.zhihu.com/question/27087744)
* [Automate the Boring Stuff with Python](https://automatetheboringstuff.com/)
* [[8w~迭代作品] 项目公示 · Issue #96 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/96)

**Comment by simonechen** [comment]
会议纪要

时间：170304 21:00-23:00

 ### 组员情况：

* 广鹤 @13416136446  广州 时间比较充裕 希望能用 python 解决实际问题, 可投入 2~3h/d
* 罗颖 @lying87 工作较忙 周末可挤出整块时间讨论分享
* 婉君 @Twanjun 汕头 目前在忙毕业论文 + 实习 可投入时间 1h/d
* 董琛 @TineeOne 北京 2~3h/d 

### 项目情况

- 缘起：小鹤即将去外地游学打工一年，需在当地找到一些打短工机会。当地论坛不定期有招聘信息发出，希望能够用程序自动抓取特定网站的招聘邮箱，匹配对应职位，定时自动发送求职邮件。

- 需求泛化：短期内找兼职、打短工的人，不太需要考虑职位需求，需要给大量招聘单位发送简历。
- 实现可能：爬取特定网站邮箱数据建立数据库，提前定义邮件模板，定时自动发送求职简历邮件。

### 项目执行方案

* MVP 的核心功能？
	- 抓取[天维论坛](http://bbs.skykiwi.com/forum.php?mod=forumdisplay&fid=55&page=1)（特定网站）中的招聘邮箱
	- 生成 list1（收件人群发的格式）
	- 部署在命令行

* 附加功能：
	- 自动发送求职邮件
	- 生成 list2（邮箱对应相应职位）
	- 回复的邮件对应 list2 的职位
	
* 技术难点：
       - 爬虫编写
       - 数据存储与提取 
 
* 参考资料：
	- 编写爬虫抓取特定网站的邮箱 [Scrapy入门教程 — Scrapy 0.24.1 文档](http://scrapy-chs.readthedocs.io/zh_CN/latest/intro/tutorial.html)  [用 Python 爬取实习信息](https://mp.weixin.qq.com/s?__biz=MzA4MjEyNTA5Mw==&mid=2652564266&idx=3&sn=c8e2d01c3162a4f677c334a932baa376&chksm=8464c360b3134a769f24670aeff63eac857e12866daa0cb703923ed669624d1381967c873f84&mpshare=1&scene=1&srcid=0104Z2uQZk2HC3SwQzLLGz0I&key=0b73c2abb17af438b2e8571dae45fb2a4243a95a11bbcebd6f4aea5f14383a4a6665b54339cf86e0ca1f4e86bc5d9946fbca1bbe292febd46ba6dfde42a7e8492764450b3bb290937f53676c33cdd337&ascene=0&uin=MTc3MjY5NzYwNA%3D%3D&devicetype=iMac+MacBookPro12%2C1+OSX+OSX+10.11.6+build(15G1217)&version=12020010&nettype=WIFI&fontScale=100&pass_ticket=WmjSCw5wxD7D21WG59N0WVSRTv0rU7iT2zw0DM9rM0JRi0nbN18H4VYnOR24FdIi)
	- 将爬取到的 Item 储存到 Pipeline [Item Pipeline — Scrapy 0.24.1 文档](http://scrapy-chs.readthedocs.io/zh_CN/latest/topics/item-pipeline.html#topics-item-pipeline)
	- 自动群发邮件 
		- [python发送各类邮件的主要方法 - 小五义 - 博客园](http://www.cnblogs.com/xiaowuyi/archive/2012/03/17/2404015.html)
		- [Python Sending Email using SMTP](https://www.tutorialspoint.com/python/python_sending_email.htm) 


 
会议流程纪要：

大家交流学习 python 初衷，都是希望能用它来解决一点实际问题，通过技术实践批量解决问题思想，剥削机器人。因为广鹤的需求比较强烈，大家就如何理解和实现需求讨论很久，查资料发现技术上不少难点，考虑到各组员目前的技术（基本卡在真实世界 API 这块），最后讨论结果，从需求出发的话，主要是爬虫编写，部署在命令行，自动发送邮件可先砍掉。



对照清单：

- [X] 了解各组员目前 py 掌握情况
- [X] 讨论可选项目 根据情况确定项目 
- [X] 各组员时间投入 
- [X] 完成项目概述
- [X] 明确 MVP 技术细节 
- [ ] 确定 github 协作开发流程
- [ ] 明确个人分工
- [ ] 进度安排

**Comment by xpgeng** [comment]
灰常棒！

- 思路已然很是清晰呐
- 整个协作流程规范也考虑进来，赞！
- 从目前的纪要来看，基本的工作量主要就是在数据的爬去上。
    - 建议 MVP 先行，先搞个小 Demo，验证下想法，试探下难点。
    - 在二期课程中，培利 利用爬虫制作了一个买房的查询系统，可以向梁教咨询下在这个过程中有哪些难点。


期待ing~~~
