### ISSUE TITLE
项目选题灵感（请大家讨论可行性）

### ISSUE THREAD

**Issue by liguanghe** [TineeOne/PythonX#2]
- 如果其他同学也有灵感，一起写在这里呀

## 灵感
1. 批量购买豆瓣豆列的书
喜欢一个系列的图书，不想一本一本的买。
调取这些网页里的书名
在京东查询
统一加入购物车
批量购买

有人见过这个么，没有的话可以写一个这样程序。

2. markdown和思维导图的关系
可否写了markdown一键转化成思维导图（在大妈网页见到过思维导图）
可否把思维导图一键转成markdowndown格式
这个阳老好像已经做到了。

3. 智能删除废话功能。没有用的自动删除
不知道打出来的多余的话放在哪里合适，打出来的都是负担。
打字快的话，产生的废物也多。
明晰哪些是没有必要的废物，也需要时间啊。
如何处理口语和书面文字中的大量废话，元话语？
感觉工作量很大，不是新手可以做到的。

4. 网页博客做成思维导图的形式，像大妈的那样。
教程写成gitbook形式，左边是目录
还有一种形式是，浮动的小型思维导图目录，点一下变大，上面是链接。浮动的，但不会乱动的。不知道加载会不会慢。
也就是把思维导图嵌套在网页上，这个我喜欢。

6. 博客全文索引

7. 实际的问题：新西兰的所有工作资料。自动整理，工作特点，每个月份有哪些工作，工作类别，工作要求，工作内容。生活内容方面，whv们关注的有哪些，本地人如何解决。海量信息处理。
8. 如何用python 成为自由职业者。我希望自己的时间是自由的，为了这个自由，需要做哪些事情？比如，如何控制自己的逃避情绪，增加心力。如何提高自己的能力。

ps：网站，挂靠最大的相关网站，突出自己的特色。利用芝麻信用评分
10. 仓储公司的分类系统如何用在个人家里，与断舍离结合。

**Comment by simonechen** [comment]
网上搜索到一些可能：

第二个已有程序实现：[Markdown文本一键转化思维导图 – Mac玩儿法](http://www.waerfa.com/convert-markdown-to-mind-map-by-workflow-service-or-pop-clip-extension)

第三个感觉像是自然语言处理之类的技术

**Comment by liguanghe** [comment]
已选题，关闭该issue。
