### ISSUE TITLE
GitHub 协同工作模式

### ISSUE THREAD

**Issue by simonechen** [TineeOne/PythonX#3]
GitHub 上两种协同工作模式，

一种是邀请协同开发，项目组成员共享同一个仓库

一种是 fork 仓库同步，代码安全系数更高，不过操作步骤较多，更适合大型开源项目

咱们目前主要做一个 Demo，我提议用邀请模式

* 发起邀请，如下图，需要大家查看邮件，同意邀请，之后就可以和其他个人仓库一样操作。
![rep-colla](http://7xso79.com1.z0.glb.clouddn.com/rep-collaborator.png)
* clone 源仓库到本地
* 修改并提交代码
* 其他成员 pull 修改到本地

如果你习惯在本地操作然后提交的话，只要记得在修改前，先 pull 一次，保证本地仓库和远程一致。

也能用 issue 发起讨论，编写 wiki，归档等~

另外，还需要每天早间或晚间，微信碰头一次，汇报今日进展。

开发人员最好能抽一段时间，实时在线交流，考虑用 YY 语音。

你有什么要补充的，欢迎在下面回复~ 今天会整理一个协作模式出来

参考资料：

* [Inviting collaborators to a personal repository - User Documentation](https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/)
* [github协同工作 | 牛头码农](http://hucaihua.applinzi.com/2016/12/02/github_cooperation/)

**Comment by liguanghe** [comment]
收到。

**Comment by simonechen** [comment]
协作模式初拟如下：

（需要先接受合作邀请，才能够操作 code、issue、wiki 等~）

- clone 源仓库到本地

`git clone git@github.com:TineeOne/PythonX.git`

- 在本地编写、修改代码、提交

`git add <file>`  将修改提交到暂存区（index）
`git commit -m <message>` 提交暂存区到仓库（repository）
`git push` 推送至远程仓库

- 获取远程仓库更新

`git pull` 拉来远程更新到主支（咱们没有分支）

- 晚间开发用微信语音碰头一次

**Comment by simonechen** [comment]
关于分工，今天跟小鹤讨论结果如下：

- 爬虫 Demo @TineeOne
- 数据库 @13416136446 

婉姑娘和颖姑娘依据时间和兴趣挑选其中的模块，双主线进行，发现问题及时交流补充。

**Comment by Twanjun** [comment]
选择爬虫Demo

**Comment by liguanghe** [comment]
作业方面，我刚刚勉强完成ch4，ch5讲的是数据库，会同时开始ch5的数据库研究，和咱们项目。
